# 服务器配置
server:
  mode: "release" # 运行模式，debug / release
  port: "8088" # 端口
  token_expire_time: 18000 # JWT token 过期时间（单位：秒）
  allowed_refers: ["localhost", "127.0.0.1"] # 允许的 referer
  limit_time: 5 # 限流时间间隔
  limit_cap: 50 # 间隔时间内最大访问次数
# 数据库配置
db:
  host: "127.0.0.1" # 主机地址
  user_name: "root" # 用户名
  password: "" # 密码
  database: "aries" # 数据库名
  port: "3306" # 端口
  time_zone: "Local" # 时区
  max_idle_conn: 10 # 最大空闲连接数
  max_open_conn: 20 # 最大打开连接数
# 日志配置
logger:
  file_name: "aries.log" # 日志文件
  max_size: 10 # 最大存储空间（MB）
  max_backups: 2 # 最大保存个数
  max_age: 1 # 最大保存时间（天）
  level: "error" # 日志级别（"debug", "info", "warn", "error","dpanic" ,"panic","fatal"）
  format: "admin" # 日志格式（"json", "admin"）
# smtp 配置（仅用于重置密码）
smtp:
  address: "smtp.qq.com" # 协议地址
  port: 465 # 端口
  account: "" # 账号
  password: "" # 密码
